import { spawn, execFileSync, type ChildProcess } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, extname, dirname, isAbsolute } from 'node:path';
import { StringDecoder } from 'node:string_decoder';
import { setTimeout as delay } from 'node:timers/promises';
import type { Executor, ExecutorInfo, Task } from '../shared/types';
import { Config, ApiError } from './config';
import { JsonLineDecoder, normalizeEvent, type ExecutionUpdate } from './executor-events';
import { resolveZcode, runZcode } from './zcode';

export interface RunResult { result: string; sessionId?: string }
export interface Runner { run(task: Task, signal: AbortSignal, onUpdate: (update: ExecutionUpdate) => void): Promise<RunResult> }
type Command = { command: string; prefix: string[] };

function resolveLauncher(path: string): Command | undefined {
  if (!existsSync(path)) return;
  if (['.exe',''].includes(extname(path).toLowerCase())) return {command:path, prefix:[]};
  if (['.js','.mjs','.cjs'].includes(extname(path).toLowerCase())) return {command:process.execPath, prefix:[path]};
  // Resolve known npm launchers without passing user text through cmd.exe.
  if (['.cmd','.ps1'].includes(extname(path).toLowerCase())) {
    const base = dirname(path);
    const candidates = [join(base,'node_modules/@anthropic-ai/claude-code/bin/claude.exe'),join(base,'node_modules/@anthropic-ai/claude-code/cli.js'),join(base,'node_modules/@openai/codex/bin/codex.js')];
    for (const candidate of candidates) { const resolved = resolveLauncher(candidate); if (resolved) return resolved; }
    // WindowsApps shim generated by npm/native installer: accept only an existing absolute exe.
    const match = readFileSync(path,'utf8').match(/^\s*"([A-Z]:\\[^"\r\n]+\.exe)"\s+%\*/mi);
    if (match && existsSync(match[1])) return {command:match[1],prefix:[]};
  }
}

export function resolveExecutor(executor: 'codex' | 'claude' | 'zcode', configured = ''): Command | undefined {
  if(executor==='zcode')return resolveZcode(configured);
  if (configured) {
    if (!isAbsolute(configured)) return;
    return resolveLauncher(configured);
  }
  const env = executor === 'codex' ? process.env.CODEX_PATH : process.env.CLAUDE_PATH;
  if (env) { const found = resolveLauncher(env); if (found) return found; }
  const home = process.env.USERPROFILE || process.env.HOME || '';
  const candidates = [join(home, '.local/bin', executor + (process.platform === 'win32' ? '.exe' : ''))];
  if (process.platform === 'win32') {
    try { candidates.push(...execFileSync('where.exe', [executor], {encoding:'utf8',windowsHide:true,timeout:5000,stdio:['ignore','pipe','ignore']}).trim().split(/\r?\n/)); } catch {}
    if (executor === 'codex') {
      const bin = join(process.env.LOCALAPPDATA || join(home,'AppData/Local'),'OpenAI/Codex/bin');
      try {
        candidates.push(...readdirSync(bin).map(name=>join(bin,name,'codex.exe')).filter(existsSync)
          .sort((a,b)=>statSync(b).mtimeMs-statSync(a).mtimeMs));
      } catch {}
    }
    if (executor === 'claude') candidates.push(join(home,'AppData/Roaming/npm/node_modules/@anthropic-ai/claude-code/bin/claude.exe'));
  } else {
    for (const folder of (process.env.PATH || '').split(':')) candidates.push(join(folder,executor));
  }
  for (const candidate of candidates) { const found = resolveLauncher(candidate); if (found) return found; }
}

export function executorCatalog(config: Config): ExecutorInfo[] {
  return (['codex','claude','zcode'] as const).map(id => {
    const found = resolveExecutor(id, config.value[`${id}Path`]);
    return {id,name:id === 'codex' ? 'Codex' : id==='zcode'?'ZCode':'Claude Code',available:!!found, detail:found ? `已找到 ${found.prefix[0] || found.command}；登录状态由运行时核验` : '未找到可执行文件，请在设置中指定绝对路径'};
  }).concat([{id:'demo' as any,name:'演示执行器',available:true,detail:'仅验证任务流程，不调用模型、不修改项目'}]);
}

function childEnv() {
  const env = {...process.env};
  for (const key of ['DEEPSEEK_API_KEY','DAYU_API_TOKEN','DAYU_INTERNAL_TOKEN','DAYU_INTERNAL_URL']) delete env[key];
  return env;
}

export function killTree(child: ChildProcess): Promise<void> {
  return new Promise(resolve => {
    if (!child.pid || child.exitCode !== null) return resolve();
    if (process.platform === 'win32') {
      const killer = spawn('taskkill.exe',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});
      killer.once('error',()=> { child.kill(); resolve(); }); killer.once('close',()=>resolve());
    } else { try { process.kill(-child.pid,'SIGKILL'); } catch { child.kill('SIGKILL'); } resolve(); }
  });
}

export function claudePermissionArgs(fullAccess: boolean): string[] {
  return fullAccess ? ['--permission-mode','bypassPermissions']
    : ['--permission-mode','dontAsk','--allowedTools','Read,Edit,Write,Glob,Grep'];
}

export class CliRunner implements Runner {
  constructor(private config: Config) {}
  async run(task: Task, signal: AbortSignal, onUpdate: (update: ExecutionUpdate)=>void): Promise<RunResult> {
    if(task.executor==='zcode')return runZcode(task,this.config.value.zcodePath,signal,onUpdate);
    if (task.executor === 'demo') {
      onUpdate({log:'演示任务：验证排队、事件和取消，不执行代码。'});
      await delay(600,undefined,{signal}); onUpdate({log:'演示进度：后台任务可以独立运行。'});
      await delay(600,undefined,{signal}); return {result:'演示流程完成。没有调用真实模型，也没有修改任何文件。'};
    }
    const executable = resolveExecutor(task.executor, this.config.value[task.executor === 'codex' ? 'codexPath' : 'claudePath']);
    if (!executable) throw new ApiError(503, `${task.executor} 不可用，请安装或设置程序路径`);
    const args = task.executor === 'codex'
      ? ['exec','--json','--skip-git-repo-check','-s','workspace-write','-c','approval_policy="never"',...(task.model ? ['-m',task.model] : []),'-']
      : ['-p','--output-format','stream-json','--verbose',...claudePermissionArgs(!!this.config.value.claudeFullAccess),...(task.model ? ['--model',task.model] : [])];
    if (signal.aborted) throw signal.reason;
    return new Promise((resolve,reject)=> {
      const child = spawn(executable.command,[...executable.prefix,...args],{cwd:task.workspace,env:childEnv(),windowsHide:true,shell:false,detached:process.platform !== 'win32',stdio:['pipe','pipe','pipe']});
      let result='', sessionId='', error='', completed=false, stderr='';
      const update = (item: ExecutionUpdate) => {
        if (item.result !== undefined) result = item.result;
        if (item.sessionId) sessionId=item.sessionId;
        if (item.error) error=item.error;
        if (item.completed) completed=true;
        onUpdate(item);
      };
      const decoder = new JsonLineDecoder(value=>update(normalizeEvent(task.executor as 'codex'|'claude',value)),line=>onUpdate({log:line.slice(0,4000)}));
      const stdoutDecoder=new StringDecoder('utf8'), stderrDecoder=new StringDecoder('utf8');
      child.stdout!.on('data',(buffer:Buffer)=>decoder.push(stdoutDecoder.write(buffer)));
      child.stderr!.on('data',(buffer:Buffer)=>{ const text=stderrDecoder.write(buffer); stderr=(stderr+text).slice(-8000); onUpdate({log:text.slice(0,2000)}); });
      const abort=()=>{ void killTree(child); };
      signal.addEventListener('abort',abort,{once:true});
      child.once('error',err=>{ signal.removeEventListener('abort',abort); reject(err); });
      child.once('close',code=>{
        signal.removeEventListener('abort',abort); decoder.push(stdoutDecoder.end()); decoder.end(); stderr+=stderrDecoder.end();
        if (signal.aborted) return reject(signal.reason || new Error('任务已取消'));
        if (code !== 0 || error || !completed) return reject(new Error(error || stderr || `执行器退出（${code}），没有收到完成事件`));
        resolve({result:result || '执行器已结束，但没有提供文本结果。请检查工作目录。',sessionId});
      });
      child.stdin!.on('error',()=>{});
      child.stdin!.end(`用户任务：\n${task.instruction}\n\n工作要求：仅在当前项目范围内工作。完成后给出修改摘要和实际验证结果；不能验证时明确说明。不要发布、推送或联系他人。遇到权限不足请报告，不要绕过权限。`);
      if (signal.aborted) abort();
    });
  }
}
